// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common/datalayer/model"
)

func newMFALoginChallenge(db *gorm.DB, opts ...gen.DOOption) mFALoginChallenge {
	_mFALoginChallenge := mFALoginChallenge{}

	_mFALoginChallenge.mFALoginChallengeDo.UseDB(db, opts...)
	_mFALoginChallenge.mFALoginChallengeDo.UseModel(&model.MFALoginChallenge{})

	tableName := _mFALoginChallenge.mFALoginChallengeDo.TableName()
	_mFALoginChallenge.ALL = field.NewAsterisk(tableName)
	_mFALoginChallenge.ID = field.NewInt64(tableName, "id")
	_mFALoginChallenge.UserID = field.NewInt64(tableName, "user_id")
	_mFALoginChallenge.Token = field.NewString(tableName, "token")
	_mFALoginChallenge.FailCount = field.NewInt(tableName, "fail_count")
	_mFALoginChallenge.MaxFailCount = field.NewInt(tableName, "max_fail_count")
	_mFALoginChallenge.ExpiredAt = field.NewTime(tableName, "expired_at")
	_mFALoginChallenge.CreatedAt = field.NewTime(tableName, "created_at")
	_mFALoginChallenge.UpdatedAt = field.NewTime(tableName, "updated_at")

	_mFALoginChallenge.fillFieldMap()

	return _mFALoginChallenge
}

type mFALoginChallenge struct {
	mFALoginChallengeDo mFALoginChallengeDo

	ALL          field.Asterisk
	ID           field.Int64  // ID
	UserID       field.Int64  // 用户ID
	Token        field.String // 临时令牌
	FailCount    field.Int    // 已经错误次数
	MaxFailCount field.Int    // 最大错误次数
	ExpiredAt    field.Time   // 过期时间
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (m mFALoginChallenge) Table(newTableName string) *mFALoginChallenge {
	m.mFALoginChallengeDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mFALoginChallenge) As(alias string) *mFALoginChallenge {
	m.mFALoginChallengeDo.DO = *(m.mFALoginChallengeDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mFALoginChallenge) updateTableName(table string) *mFALoginChallenge {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.UserID = field.NewInt64(table, "user_id")
	m.Token = field.NewString(table, "token")
	m.FailCount = field.NewInt(table, "fail_count")
	m.MaxFailCount = field.NewInt(table, "max_fail_count")
	m.ExpiredAt = field.NewTime(table, "expired_at")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *mFALoginChallenge) WithContext(ctx context.Context) IMFALoginChallengeDo {
	return m.mFALoginChallengeDo.WithContext(ctx)
}

func (m mFALoginChallenge) TableName() string { return m.mFALoginChallengeDo.TableName() }

func (m mFALoginChallenge) Alias() string { return m.mFALoginChallengeDo.Alias() }

func (m mFALoginChallenge) Columns(cols ...field.Expr) gen.Columns {
	return m.mFALoginChallengeDo.Columns(cols...)
}

func (m *mFALoginChallenge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mFALoginChallenge) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["id"] = m.ID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["token"] = m.Token
	m.fieldMap["fail_count"] = m.FailCount
	m.fieldMap["max_fail_count"] = m.MaxFailCount
	m.fieldMap["expired_at"] = m.ExpiredAt
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m mFALoginChallenge) clone(db *gorm.DB) mFALoginChallenge {
	m.mFALoginChallengeDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mFALoginChallenge) replaceDB(db *gorm.DB) mFALoginChallenge {
	m.mFALoginChallengeDo.ReplaceDB(db)
	return m
}

type mFALoginChallengeDo struct{ gen.DO }

type IMFALoginChallengeDo interface {
	gen.SubQuery
	Debug() IMFALoginChallengeDo
	WithContext(ctx context.Context) IMFALoginChallengeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMFALoginChallengeDo
	WriteDB() IMFALoginChallengeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMFALoginChallengeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMFALoginChallengeDo
	Not(conds ...gen.Condition) IMFALoginChallengeDo
	Or(conds ...gen.Condition) IMFALoginChallengeDo
	Select(conds ...field.Expr) IMFALoginChallengeDo
	Where(conds ...gen.Condition) IMFALoginChallengeDo
	Order(conds ...field.Expr) IMFALoginChallengeDo
	Distinct(cols ...field.Expr) IMFALoginChallengeDo
	Omit(cols ...field.Expr) IMFALoginChallengeDo
	Join(table schema.Tabler, on ...field.Expr) IMFALoginChallengeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMFALoginChallengeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMFALoginChallengeDo
	Group(cols ...field.Expr) IMFALoginChallengeDo
	Having(conds ...gen.Condition) IMFALoginChallengeDo
	Limit(limit int) IMFALoginChallengeDo
	Offset(offset int) IMFALoginChallengeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMFALoginChallengeDo
	Unscoped() IMFALoginChallengeDo
	Create(values ...*model.MFALoginChallenge) error
	CreateInBatches(values []*model.MFALoginChallenge, batchSize int) error
	Save(values ...*model.MFALoginChallenge) error
	First() (*model.MFALoginChallenge, error)
	Take() (*model.MFALoginChallenge, error)
	Last() (*model.MFALoginChallenge, error)
	Find() ([]*model.MFALoginChallenge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MFALoginChallenge, err error)
	FindInBatches(result *[]*model.MFALoginChallenge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MFALoginChallenge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMFALoginChallengeDo
	Assign(attrs ...field.AssignExpr) IMFALoginChallengeDo
	Joins(fields ...field.RelationField) IMFALoginChallengeDo
	Preload(fields ...field.RelationField) IMFALoginChallengeDo
	FirstOrInit() (*model.MFALoginChallenge, error)
	FirstOrCreate() (*model.MFALoginChallenge, error)
	FindByPage(offset int, limit int) (result []*model.MFALoginChallenge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMFALoginChallengeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mFALoginChallengeDo) Debug() IMFALoginChallengeDo {
	return m.withDO(m.DO.Debug())
}

func (m mFALoginChallengeDo) WithContext(ctx context.Context) IMFALoginChallengeDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mFALoginChallengeDo) ReadDB() IMFALoginChallengeDo {
	return m.Clauses(dbresolver.Read)
}

func (m mFALoginChallengeDo) WriteDB() IMFALoginChallengeDo {
	return m.Clauses(dbresolver.Write)
}

func (m mFALoginChallengeDo) Session(config *gorm.Session) IMFALoginChallengeDo {
	return m.withDO(m.DO.Session(config))
}

func (m mFALoginChallengeDo) Clauses(conds ...clause.Expression) IMFALoginChallengeDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mFALoginChallengeDo) Returning(value interface{}, columns ...string) IMFALoginChallengeDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mFALoginChallengeDo) Not(conds ...gen.Condition) IMFALoginChallengeDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mFALoginChallengeDo) Or(conds ...gen.Condition) IMFALoginChallengeDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mFALoginChallengeDo) Select(conds ...field.Expr) IMFALoginChallengeDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mFALoginChallengeDo) Where(conds ...gen.Condition) IMFALoginChallengeDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mFALoginChallengeDo) Order(conds ...field.Expr) IMFALoginChallengeDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mFALoginChallengeDo) Distinct(cols ...field.Expr) IMFALoginChallengeDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mFALoginChallengeDo) Omit(cols ...field.Expr) IMFALoginChallengeDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mFALoginChallengeDo) Join(table schema.Tabler, on ...field.Expr) IMFALoginChallengeDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mFALoginChallengeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMFALoginChallengeDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mFALoginChallengeDo) RightJoin(table schema.Tabler, on ...field.Expr) IMFALoginChallengeDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mFALoginChallengeDo) Group(cols ...field.Expr) IMFALoginChallengeDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mFALoginChallengeDo) Having(conds ...gen.Condition) IMFALoginChallengeDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mFALoginChallengeDo) Limit(limit int) IMFALoginChallengeDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mFALoginChallengeDo) Offset(offset int) IMFALoginChallengeDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mFALoginChallengeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMFALoginChallengeDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mFALoginChallengeDo) Unscoped() IMFALoginChallengeDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mFALoginChallengeDo) Create(values ...*model.MFALoginChallenge) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mFALoginChallengeDo) CreateInBatches(values []*model.MFALoginChallenge, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mFALoginChallengeDo) Save(values ...*model.MFALoginChallenge) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mFALoginChallengeDo) First() (*model.MFALoginChallenge, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MFALoginChallenge), nil
	}
}

func (m mFALoginChallengeDo) Take() (*model.MFALoginChallenge, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MFALoginChallenge), nil
	}
}

func (m mFALoginChallengeDo) Last() (*model.MFALoginChallenge, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MFALoginChallenge), nil
	}
}

func (m mFALoginChallengeDo) Find() ([]*model.MFALoginChallenge, error) {
	result, err := m.DO.Find()
	return result.([]*model.MFALoginChallenge), err
}

func (m mFALoginChallengeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MFALoginChallenge, err error) {
	buf := make([]*model.MFALoginChallenge, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mFALoginChallengeDo) FindInBatches(result *[]*model.MFALoginChallenge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mFALoginChallengeDo) Attrs(attrs ...field.AssignExpr) IMFALoginChallengeDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mFALoginChallengeDo) Assign(attrs ...field.AssignExpr) IMFALoginChallengeDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mFALoginChallengeDo) Joins(fields ...field.RelationField) IMFALoginChallengeDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mFALoginChallengeDo) Preload(fields ...field.RelationField) IMFALoginChallengeDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mFALoginChallengeDo) FirstOrInit() (*model.MFALoginChallenge, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MFALoginChallenge), nil
	}
}

func (m mFALoginChallengeDo) FirstOrCreate() (*model.MFALoginChallenge, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MFALoginChallenge), nil
	}
}

func (m mFALoginChallengeDo) FindByPage(offset int, limit int) (result []*model.MFALoginChallenge, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mFALoginChallengeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mFALoginChallengeDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mFALoginChallengeDo) Delete(models ...*model.MFALoginChallenge) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mFALoginChallengeDo) withDO(do gen.Dao) *mFALoginChallengeDo {
	m.DO = *do.(*gen.DO)
	return m
}
