// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common/datalayer/model"
)

func newMinionGroup(db *gorm.DB, opts ...gen.DOOption) minionGroup {
	_minionGroup := minionGroup{}

	_minionGroup.minionGroupDo.UseDB(db, opts...)
	_minionGroup.minionGroupDo.UseModel(&model.MinionGroup{})

	tableName := _minionGroup.minionGroupDo.TableName()
	_minionGroup.ALL = field.NewAsterisk(tableName)
	_minionGroup.ID = field.NewInt64(tableName, "id")
	_minionGroup.MinionID = field.NewInt64(tableName, "minion_id")
	_minionGroup.Inet = field.NewString(tableName, "inet")
	_minionGroup.Name = field.NewString(tableName, "name")
	_minionGroup.GID = field.NewString(tableName, "gid")
	_minionGroup.Description = field.NewString(tableName, "description")
	_minionGroup.CreatedAt = field.NewTime(tableName, "created_at")
	_minionGroup.UpdatedAt = field.NewTime(tableName, "updated_at")

	_minionGroup.fillFieldMap()

	return _minionGroup
}

type minionGroup struct {
	minionGroupDo minionGroupDo

	ALL         field.Asterisk
	ID          field.Int64 // ID
	MinionID    field.Int64
	Inet        field.String
	Name        field.String
	GID         field.String
	Description field.String
	CreatedAt   field.Time // 创建时间
	UpdatedAt   field.Time // 更新时间

	fieldMap map[string]field.Expr
}

func (m minionGroup) Table(newTableName string) *minionGroup {
	m.minionGroupDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m minionGroup) As(alias string) *minionGroup {
	m.minionGroupDo.DO = *(m.minionGroupDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *minionGroup) updateTableName(table string) *minionGroup {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MinionID = field.NewInt64(table, "minion_id")
	m.Inet = field.NewString(table, "inet")
	m.Name = field.NewString(table, "name")
	m.GID = field.NewString(table, "gid")
	m.Description = field.NewString(table, "description")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *minionGroup) WithContext(ctx context.Context) IMinionGroupDo {
	return m.minionGroupDo.WithContext(ctx)
}

func (m minionGroup) TableName() string { return m.minionGroupDo.TableName() }

func (m minionGroup) Alias() string { return m.minionGroupDo.Alias() }

func (m minionGroup) Columns(cols ...field.Expr) gen.Columns { return m.minionGroupDo.Columns(cols...) }

func (m *minionGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *minionGroup) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["id"] = m.ID
	m.fieldMap["minion_id"] = m.MinionID
	m.fieldMap["inet"] = m.Inet
	m.fieldMap["name"] = m.Name
	m.fieldMap["gid"] = m.GID
	m.fieldMap["description"] = m.Description
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m minionGroup) clone(db *gorm.DB) minionGroup {
	m.minionGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m minionGroup) replaceDB(db *gorm.DB) minionGroup {
	m.minionGroupDo.ReplaceDB(db)
	return m
}

type minionGroupDo struct{ gen.DO }

type IMinionGroupDo interface {
	gen.SubQuery
	Debug() IMinionGroupDo
	WithContext(ctx context.Context) IMinionGroupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMinionGroupDo
	WriteDB() IMinionGroupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMinionGroupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMinionGroupDo
	Not(conds ...gen.Condition) IMinionGroupDo
	Or(conds ...gen.Condition) IMinionGroupDo
	Select(conds ...field.Expr) IMinionGroupDo
	Where(conds ...gen.Condition) IMinionGroupDo
	Order(conds ...field.Expr) IMinionGroupDo
	Distinct(cols ...field.Expr) IMinionGroupDo
	Omit(cols ...field.Expr) IMinionGroupDo
	Join(table schema.Tabler, on ...field.Expr) IMinionGroupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMinionGroupDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMinionGroupDo
	Group(cols ...field.Expr) IMinionGroupDo
	Having(conds ...gen.Condition) IMinionGroupDo
	Limit(limit int) IMinionGroupDo
	Offset(offset int) IMinionGroupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMinionGroupDo
	Unscoped() IMinionGroupDo
	Create(values ...*model.MinionGroup) error
	CreateInBatches(values []*model.MinionGroup, batchSize int) error
	Save(values ...*model.MinionGroup) error
	First() (*model.MinionGroup, error)
	Take() (*model.MinionGroup, error)
	Last() (*model.MinionGroup, error)
	Find() ([]*model.MinionGroup, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MinionGroup, err error)
	FindInBatches(result *[]*model.MinionGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MinionGroup) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMinionGroupDo
	Assign(attrs ...field.AssignExpr) IMinionGroupDo
	Joins(fields ...field.RelationField) IMinionGroupDo
	Preload(fields ...field.RelationField) IMinionGroupDo
	FirstOrInit() (*model.MinionGroup, error)
	FirstOrCreate() (*model.MinionGroup, error)
	FindByPage(offset int, limit int) (result []*model.MinionGroup, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMinionGroupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m minionGroupDo) Debug() IMinionGroupDo {
	return m.withDO(m.DO.Debug())
}

func (m minionGroupDo) WithContext(ctx context.Context) IMinionGroupDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m minionGroupDo) ReadDB() IMinionGroupDo {
	return m.Clauses(dbresolver.Read)
}

func (m minionGroupDo) WriteDB() IMinionGroupDo {
	return m.Clauses(dbresolver.Write)
}

func (m minionGroupDo) Session(config *gorm.Session) IMinionGroupDo {
	return m.withDO(m.DO.Session(config))
}

func (m minionGroupDo) Clauses(conds ...clause.Expression) IMinionGroupDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m minionGroupDo) Returning(value interface{}, columns ...string) IMinionGroupDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m minionGroupDo) Not(conds ...gen.Condition) IMinionGroupDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m minionGroupDo) Or(conds ...gen.Condition) IMinionGroupDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m minionGroupDo) Select(conds ...field.Expr) IMinionGroupDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m minionGroupDo) Where(conds ...gen.Condition) IMinionGroupDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m minionGroupDo) Order(conds ...field.Expr) IMinionGroupDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m minionGroupDo) Distinct(cols ...field.Expr) IMinionGroupDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m minionGroupDo) Omit(cols ...field.Expr) IMinionGroupDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m minionGroupDo) Join(table schema.Tabler, on ...field.Expr) IMinionGroupDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m minionGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMinionGroupDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m minionGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) IMinionGroupDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m minionGroupDo) Group(cols ...field.Expr) IMinionGroupDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m minionGroupDo) Having(conds ...gen.Condition) IMinionGroupDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m minionGroupDo) Limit(limit int) IMinionGroupDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m minionGroupDo) Offset(offset int) IMinionGroupDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m minionGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMinionGroupDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m minionGroupDo) Unscoped() IMinionGroupDo {
	return m.withDO(m.DO.Unscoped())
}

func (m minionGroupDo) Create(values ...*model.MinionGroup) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m minionGroupDo) CreateInBatches(values []*model.MinionGroup, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m minionGroupDo) Save(values ...*model.MinionGroup) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m minionGroupDo) First() (*model.MinionGroup, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionGroup), nil
	}
}

func (m minionGroupDo) Take() (*model.MinionGroup, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionGroup), nil
	}
}

func (m minionGroupDo) Last() (*model.MinionGroup, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionGroup), nil
	}
}

func (m minionGroupDo) Find() ([]*model.MinionGroup, error) {
	result, err := m.DO.Find()
	return result.([]*model.MinionGroup), err
}

func (m minionGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MinionGroup, err error) {
	buf := make([]*model.MinionGroup, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m minionGroupDo) FindInBatches(result *[]*model.MinionGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m minionGroupDo) Attrs(attrs ...field.AssignExpr) IMinionGroupDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m minionGroupDo) Assign(attrs ...field.AssignExpr) IMinionGroupDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m minionGroupDo) Joins(fields ...field.RelationField) IMinionGroupDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m minionGroupDo) Preload(fields ...field.RelationField) IMinionGroupDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m minionGroupDo) FirstOrInit() (*model.MinionGroup, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionGroup), nil
	}
}

func (m minionGroupDo) FirstOrCreate() (*model.MinionGroup, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionGroup), nil
	}
}

func (m minionGroupDo) FindByPage(offset int, limit int) (result []*model.MinionGroup, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m minionGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m minionGroupDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m minionGroupDo) Delete(models ...*model.MinionGroup) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *minionGroupDo) withDO(do gen.Dao) *minionGroupDo {
	m.DO = *do.(*gen.DO)
	return m
}
