// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common/datalayer/model"
)

func newMinionSubstanceExclude(db *gorm.DB, opts ...gen.DOOption) minionSubstanceExclude {
	_minionSubstanceExclude := minionSubstanceExclude{}

	_minionSubstanceExclude.minionSubstanceExcludeDo.UseDB(db, opts...)
	_minionSubstanceExclude.minionSubstanceExcludeDo.UseModel(&model.MinionSubstanceExclude{})

	tableName := _minionSubstanceExclude.minionSubstanceExcludeDo.TableName()
	_minionSubstanceExclude.ALL = field.NewAsterisk(tableName)
	_minionSubstanceExclude.ID = field.NewInt64(tableName, "id")
	_minionSubstanceExclude.MinionID = field.NewInt64(tableName, "minion_id")
	_minionSubstanceExclude.SubstanceID = field.NewInt64(tableName, "substance_id")

	_minionSubstanceExclude.fillFieldMap()

	return _minionSubstanceExclude
}

type minionSubstanceExclude struct {
	minionSubstanceExcludeDo minionSubstanceExcludeDo

	ALL         field.Asterisk
	ID          field.Int64 // ID
	MinionID    field.Int64
	SubstanceID field.Int64

	fieldMap map[string]field.Expr
}

func (m minionSubstanceExclude) Table(newTableName string) *minionSubstanceExclude {
	m.minionSubstanceExcludeDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m minionSubstanceExclude) As(alias string) *minionSubstanceExclude {
	m.minionSubstanceExcludeDo.DO = *(m.minionSubstanceExcludeDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *minionSubstanceExclude) updateTableName(table string) *minionSubstanceExclude {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MinionID = field.NewInt64(table, "minion_id")
	m.SubstanceID = field.NewInt64(table, "substance_id")

	m.fillFieldMap()

	return m
}

func (m *minionSubstanceExclude) WithContext(ctx context.Context) IMinionSubstanceExcludeDo {
	return m.minionSubstanceExcludeDo.WithContext(ctx)
}

func (m minionSubstanceExclude) TableName() string { return m.minionSubstanceExcludeDo.TableName() }

func (m minionSubstanceExclude) Alias() string { return m.minionSubstanceExcludeDo.Alias() }

func (m minionSubstanceExclude) Columns(cols ...field.Expr) gen.Columns {
	return m.minionSubstanceExcludeDo.Columns(cols...)
}

func (m *minionSubstanceExclude) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *minionSubstanceExclude) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 3)
	m.fieldMap["id"] = m.ID
	m.fieldMap["minion_id"] = m.MinionID
	m.fieldMap["substance_id"] = m.SubstanceID
}

func (m minionSubstanceExclude) clone(db *gorm.DB) minionSubstanceExclude {
	m.minionSubstanceExcludeDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m minionSubstanceExclude) replaceDB(db *gorm.DB) minionSubstanceExclude {
	m.minionSubstanceExcludeDo.ReplaceDB(db)
	return m
}

type minionSubstanceExcludeDo struct{ gen.DO }

type IMinionSubstanceExcludeDo interface {
	gen.SubQuery
	Debug() IMinionSubstanceExcludeDo
	WithContext(ctx context.Context) IMinionSubstanceExcludeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMinionSubstanceExcludeDo
	WriteDB() IMinionSubstanceExcludeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMinionSubstanceExcludeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMinionSubstanceExcludeDo
	Not(conds ...gen.Condition) IMinionSubstanceExcludeDo
	Or(conds ...gen.Condition) IMinionSubstanceExcludeDo
	Select(conds ...field.Expr) IMinionSubstanceExcludeDo
	Where(conds ...gen.Condition) IMinionSubstanceExcludeDo
	Order(conds ...field.Expr) IMinionSubstanceExcludeDo
	Distinct(cols ...field.Expr) IMinionSubstanceExcludeDo
	Omit(cols ...field.Expr) IMinionSubstanceExcludeDo
	Join(table schema.Tabler, on ...field.Expr) IMinionSubstanceExcludeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMinionSubstanceExcludeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMinionSubstanceExcludeDo
	Group(cols ...field.Expr) IMinionSubstanceExcludeDo
	Having(conds ...gen.Condition) IMinionSubstanceExcludeDo
	Limit(limit int) IMinionSubstanceExcludeDo
	Offset(offset int) IMinionSubstanceExcludeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMinionSubstanceExcludeDo
	Unscoped() IMinionSubstanceExcludeDo
	Create(values ...*model.MinionSubstanceExclude) error
	CreateInBatches(values []*model.MinionSubstanceExclude, batchSize int) error
	Save(values ...*model.MinionSubstanceExclude) error
	First() (*model.MinionSubstanceExclude, error)
	Take() (*model.MinionSubstanceExclude, error)
	Last() (*model.MinionSubstanceExclude, error)
	Find() ([]*model.MinionSubstanceExclude, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MinionSubstanceExclude, err error)
	FindInBatches(result *[]*model.MinionSubstanceExclude, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MinionSubstanceExclude) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMinionSubstanceExcludeDo
	Assign(attrs ...field.AssignExpr) IMinionSubstanceExcludeDo
	Joins(fields ...field.RelationField) IMinionSubstanceExcludeDo
	Preload(fields ...field.RelationField) IMinionSubstanceExcludeDo
	FirstOrInit() (*model.MinionSubstanceExclude, error)
	FirstOrCreate() (*model.MinionSubstanceExclude, error)
	FindByPage(offset int, limit int) (result []*model.MinionSubstanceExclude, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMinionSubstanceExcludeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m minionSubstanceExcludeDo) Debug() IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Debug())
}

func (m minionSubstanceExcludeDo) WithContext(ctx context.Context) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m minionSubstanceExcludeDo) ReadDB() IMinionSubstanceExcludeDo {
	return m.Clauses(dbresolver.Read)
}

func (m minionSubstanceExcludeDo) WriteDB() IMinionSubstanceExcludeDo {
	return m.Clauses(dbresolver.Write)
}

func (m minionSubstanceExcludeDo) Session(config *gorm.Session) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Session(config))
}

func (m minionSubstanceExcludeDo) Clauses(conds ...clause.Expression) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m minionSubstanceExcludeDo) Returning(value interface{}, columns ...string) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m minionSubstanceExcludeDo) Not(conds ...gen.Condition) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m minionSubstanceExcludeDo) Or(conds ...gen.Condition) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m minionSubstanceExcludeDo) Select(conds ...field.Expr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m minionSubstanceExcludeDo) Where(conds ...gen.Condition) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m minionSubstanceExcludeDo) Order(conds ...field.Expr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m minionSubstanceExcludeDo) Distinct(cols ...field.Expr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m minionSubstanceExcludeDo) Omit(cols ...field.Expr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m minionSubstanceExcludeDo) Join(table schema.Tabler, on ...field.Expr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m minionSubstanceExcludeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m minionSubstanceExcludeDo) RightJoin(table schema.Tabler, on ...field.Expr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m minionSubstanceExcludeDo) Group(cols ...field.Expr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m minionSubstanceExcludeDo) Having(conds ...gen.Condition) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m minionSubstanceExcludeDo) Limit(limit int) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m minionSubstanceExcludeDo) Offset(offset int) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m minionSubstanceExcludeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m minionSubstanceExcludeDo) Unscoped() IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Unscoped())
}

func (m minionSubstanceExcludeDo) Create(values ...*model.MinionSubstanceExclude) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m minionSubstanceExcludeDo) CreateInBatches(values []*model.MinionSubstanceExclude, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m minionSubstanceExcludeDo) Save(values ...*model.MinionSubstanceExclude) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m minionSubstanceExcludeDo) First() (*model.MinionSubstanceExclude, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionSubstanceExclude), nil
	}
}

func (m minionSubstanceExcludeDo) Take() (*model.MinionSubstanceExclude, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionSubstanceExclude), nil
	}
}

func (m minionSubstanceExcludeDo) Last() (*model.MinionSubstanceExclude, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionSubstanceExclude), nil
	}
}

func (m minionSubstanceExcludeDo) Find() ([]*model.MinionSubstanceExclude, error) {
	result, err := m.DO.Find()
	return result.([]*model.MinionSubstanceExclude), err
}

func (m minionSubstanceExcludeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MinionSubstanceExclude, err error) {
	buf := make([]*model.MinionSubstanceExclude, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m minionSubstanceExcludeDo) FindInBatches(result *[]*model.MinionSubstanceExclude, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m minionSubstanceExcludeDo) Attrs(attrs ...field.AssignExpr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m minionSubstanceExcludeDo) Assign(attrs ...field.AssignExpr) IMinionSubstanceExcludeDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m minionSubstanceExcludeDo) Joins(fields ...field.RelationField) IMinionSubstanceExcludeDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m minionSubstanceExcludeDo) Preload(fields ...field.RelationField) IMinionSubstanceExcludeDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m minionSubstanceExcludeDo) FirstOrInit() (*model.MinionSubstanceExclude, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionSubstanceExclude), nil
	}
}

func (m minionSubstanceExcludeDo) FirstOrCreate() (*model.MinionSubstanceExclude, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionSubstanceExclude), nil
	}
}

func (m minionSubstanceExcludeDo) FindByPage(offset int, limit int) (result []*model.MinionSubstanceExclude, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m minionSubstanceExcludeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m minionSubstanceExcludeDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m minionSubstanceExcludeDo) Delete(models ...*model.MinionSubstanceExclude) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *minionSubstanceExcludeDo) withDO(do gen.Dao) *minionSubstanceExcludeDo {
	m.DO = *do.(*gen.DO)
	return m
}
