// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common/datalayer/model"
)

func newPyroscope(db *gorm.DB, opts ...gen.DOOption) pyroscope {
	_pyroscope := pyroscope{}

	_pyroscope.pyroscopeDo.UseDB(db, opts...)
	_pyroscope.pyroscopeDo.UseModel(&model.Pyroscope{})

	tableName := _pyroscope.pyroscopeDo.TableName()
	_pyroscope.ALL = field.NewAsterisk(tableName)
	_pyroscope.ID = field.NewInt64(tableName, "id")
	_pyroscope.Enabled = field.NewBool(tableName, "enabled")
	_pyroscope.URL = field.NewString(tableName, "url")
	_pyroscope.Username = field.NewString(tableName, "username")
	_pyroscope.Password = field.NewString(tableName, "password")
	_pyroscope.Header = field.NewField(tableName, "header")
	_pyroscope.CreatedAt = field.NewTime(tableName, "created_at")
	_pyroscope.UpdatedAt = field.NewTime(tableName, "updated_at")

	_pyroscope.fillFieldMap()

	return _pyroscope
}

type pyroscope struct {
	pyroscopeDo pyroscopeDo

	ALL       field.Asterisk
	ID        field.Int64  // ID
	Enabled   field.Bool   // 是否启用
	URL       field.String // 推送地址
	Username  field.String // 认证用户
	Password  field.String // 认证密码
	Header    field.Field  // Header
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (p pyroscope) Table(newTableName string) *pyroscope {
	p.pyroscopeDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pyroscope) As(alias string) *pyroscope {
	p.pyroscopeDo.DO = *(p.pyroscopeDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pyroscope) updateTableName(table string) *pyroscope {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Enabled = field.NewBool(table, "enabled")
	p.URL = field.NewString(table, "url")
	p.Username = field.NewString(table, "username")
	p.Password = field.NewString(table, "password")
	p.Header = field.NewField(table, "header")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *pyroscope) WithContext(ctx context.Context) IPyroscopeDo {
	return p.pyroscopeDo.WithContext(ctx)
}

func (p pyroscope) TableName() string { return p.pyroscopeDo.TableName() }

func (p pyroscope) Alias() string { return p.pyroscopeDo.Alias() }

func (p pyroscope) Columns(cols ...field.Expr) gen.Columns { return p.pyroscopeDo.Columns(cols...) }

func (p *pyroscope) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pyroscope) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["enabled"] = p.Enabled
	p.fieldMap["url"] = p.URL
	p.fieldMap["username"] = p.Username
	p.fieldMap["password"] = p.Password
	p.fieldMap["header"] = p.Header
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p pyroscope) clone(db *gorm.DB) pyroscope {
	p.pyroscopeDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pyroscope) replaceDB(db *gorm.DB) pyroscope {
	p.pyroscopeDo.ReplaceDB(db)
	return p
}

type pyroscopeDo struct{ gen.DO }

type IPyroscopeDo interface {
	gen.SubQuery
	Debug() IPyroscopeDo
	WithContext(ctx context.Context) IPyroscopeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPyroscopeDo
	WriteDB() IPyroscopeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPyroscopeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPyroscopeDo
	Not(conds ...gen.Condition) IPyroscopeDo
	Or(conds ...gen.Condition) IPyroscopeDo
	Select(conds ...field.Expr) IPyroscopeDo
	Where(conds ...gen.Condition) IPyroscopeDo
	Order(conds ...field.Expr) IPyroscopeDo
	Distinct(cols ...field.Expr) IPyroscopeDo
	Omit(cols ...field.Expr) IPyroscopeDo
	Join(table schema.Tabler, on ...field.Expr) IPyroscopeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPyroscopeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPyroscopeDo
	Group(cols ...field.Expr) IPyroscopeDo
	Having(conds ...gen.Condition) IPyroscopeDo
	Limit(limit int) IPyroscopeDo
	Offset(offset int) IPyroscopeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPyroscopeDo
	Unscoped() IPyroscopeDo
	Create(values ...*model.Pyroscope) error
	CreateInBatches(values []*model.Pyroscope, batchSize int) error
	Save(values ...*model.Pyroscope) error
	First() (*model.Pyroscope, error)
	Take() (*model.Pyroscope, error)
	Last() (*model.Pyroscope, error)
	Find() ([]*model.Pyroscope, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Pyroscope, err error)
	FindInBatches(result *[]*model.Pyroscope, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Pyroscope) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPyroscopeDo
	Assign(attrs ...field.AssignExpr) IPyroscopeDo
	Joins(fields ...field.RelationField) IPyroscopeDo
	Preload(fields ...field.RelationField) IPyroscopeDo
	FirstOrInit() (*model.Pyroscope, error)
	FirstOrCreate() (*model.Pyroscope, error)
	FindByPage(offset int, limit int) (result []*model.Pyroscope, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPyroscopeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p pyroscopeDo) Debug() IPyroscopeDo {
	return p.withDO(p.DO.Debug())
}

func (p pyroscopeDo) WithContext(ctx context.Context) IPyroscopeDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pyroscopeDo) ReadDB() IPyroscopeDo {
	return p.Clauses(dbresolver.Read)
}

func (p pyroscopeDo) WriteDB() IPyroscopeDo {
	return p.Clauses(dbresolver.Write)
}

func (p pyroscopeDo) Session(config *gorm.Session) IPyroscopeDo {
	return p.withDO(p.DO.Session(config))
}

func (p pyroscopeDo) Clauses(conds ...clause.Expression) IPyroscopeDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pyroscopeDo) Returning(value interface{}, columns ...string) IPyroscopeDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pyroscopeDo) Not(conds ...gen.Condition) IPyroscopeDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pyroscopeDo) Or(conds ...gen.Condition) IPyroscopeDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pyroscopeDo) Select(conds ...field.Expr) IPyroscopeDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pyroscopeDo) Where(conds ...gen.Condition) IPyroscopeDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pyroscopeDo) Order(conds ...field.Expr) IPyroscopeDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pyroscopeDo) Distinct(cols ...field.Expr) IPyroscopeDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pyroscopeDo) Omit(cols ...field.Expr) IPyroscopeDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pyroscopeDo) Join(table schema.Tabler, on ...field.Expr) IPyroscopeDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pyroscopeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPyroscopeDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pyroscopeDo) RightJoin(table schema.Tabler, on ...field.Expr) IPyroscopeDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pyroscopeDo) Group(cols ...field.Expr) IPyroscopeDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pyroscopeDo) Having(conds ...gen.Condition) IPyroscopeDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pyroscopeDo) Limit(limit int) IPyroscopeDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pyroscopeDo) Offset(offset int) IPyroscopeDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pyroscopeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPyroscopeDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pyroscopeDo) Unscoped() IPyroscopeDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pyroscopeDo) Create(values ...*model.Pyroscope) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pyroscopeDo) CreateInBatches(values []*model.Pyroscope, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pyroscopeDo) Save(values ...*model.Pyroscope) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pyroscopeDo) First() (*model.Pyroscope, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pyroscope), nil
	}
}

func (p pyroscopeDo) Take() (*model.Pyroscope, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pyroscope), nil
	}
}

func (p pyroscopeDo) Last() (*model.Pyroscope, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pyroscope), nil
	}
}

func (p pyroscopeDo) Find() ([]*model.Pyroscope, error) {
	result, err := p.DO.Find()
	return result.([]*model.Pyroscope), err
}

func (p pyroscopeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Pyroscope, err error) {
	buf := make([]*model.Pyroscope, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pyroscopeDo) FindInBatches(result *[]*model.Pyroscope, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pyroscopeDo) Attrs(attrs ...field.AssignExpr) IPyroscopeDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pyroscopeDo) Assign(attrs ...field.AssignExpr) IPyroscopeDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pyroscopeDo) Joins(fields ...field.RelationField) IPyroscopeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pyroscopeDo) Preload(fields ...field.RelationField) IPyroscopeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pyroscopeDo) FirstOrInit() (*model.Pyroscope, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pyroscope), nil
	}
}

func (p pyroscopeDo) FirstOrCreate() (*model.Pyroscope, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pyroscope), nil
	}
}

func (p pyroscopeDo) FindByPage(offset int, limit int) (result []*model.Pyroscope, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pyroscopeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pyroscopeDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pyroscopeDo) Delete(models ...*model.Pyroscope) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pyroscopeDo) withDO(do gen.Dao) *pyroscopeDo {
	p.DO = *do.(*gen.DO)
	return p
}
