// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common/datalayer/model"
)

func newRiskDNS(db *gorm.DB, opts ...gen.DOOption) riskDNS {
	_riskDNS := riskDNS{}

	_riskDNS.riskDNSDo.UseDB(db, opts...)
	_riskDNS.riskDNSDo.UseModel(&model.RiskDNS{})

	tableName := _riskDNS.riskDNSDo.TableName()
	_riskDNS.ALL = field.NewAsterisk(tableName)
	_riskDNS.ID = field.NewInt64(tableName, "id")
	_riskDNS.Domain = field.NewString(tableName, "domain")
	_riskDNS.Kind = field.NewString(tableName, "kind")
	_riskDNS.Origin = field.NewString(tableName, "origin")
	_riskDNS.BeforeAt = field.NewTime(tableName, "before_at")
	_riskDNS.CreatedAt = field.NewTime(tableName, "created_at")
	_riskDNS.UpdatedAt = field.NewTime(tableName, "updated_at")

	_riskDNS.fillFieldMap()

	return _riskDNS
}

type riskDNS struct {
	riskDNSDo riskDNSDo

	ALL       field.Asterisk
	ID        field.Int64 // ID
	Domain    field.String
	Kind      field.String
	Origin    field.String
	BeforeAt  field.Time
	CreatedAt field.Time // 创建时间
	UpdatedAt field.Time // 更新时间

	fieldMap map[string]field.Expr
}

func (r riskDNS) Table(newTableName string) *riskDNS {
	r.riskDNSDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r riskDNS) As(alias string) *riskDNS {
	r.riskDNSDo.DO = *(r.riskDNSDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *riskDNS) updateTableName(table string) *riskDNS {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.Domain = field.NewString(table, "domain")
	r.Kind = field.NewString(table, "kind")
	r.Origin = field.NewString(table, "origin")
	r.BeforeAt = field.NewTime(table, "before_at")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *riskDNS) WithContext(ctx context.Context) IRiskDNSDo { return r.riskDNSDo.WithContext(ctx) }

func (r riskDNS) TableName() string { return r.riskDNSDo.TableName() }

func (r riskDNS) Alias() string { return r.riskDNSDo.Alias() }

func (r riskDNS) Columns(cols ...field.Expr) gen.Columns { return r.riskDNSDo.Columns(cols...) }

func (r *riskDNS) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *riskDNS) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["domain"] = r.Domain
	r.fieldMap["kind"] = r.Kind
	r.fieldMap["origin"] = r.Origin
	r.fieldMap["before_at"] = r.BeforeAt
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r riskDNS) clone(db *gorm.DB) riskDNS {
	r.riskDNSDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r riskDNS) replaceDB(db *gorm.DB) riskDNS {
	r.riskDNSDo.ReplaceDB(db)
	return r
}

type riskDNSDo struct{ gen.DO }

type IRiskDNSDo interface {
	gen.SubQuery
	Debug() IRiskDNSDo
	WithContext(ctx context.Context) IRiskDNSDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRiskDNSDo
	WriteDB() IRiskDNSDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRiskDNSDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRiskDNSDo
	Not(conds ...gen.Condition) IRiskDNSDo
	Or(conds ...gen.Condition) IRiskDNSDo
	Select(conds ...field.Expr) IRiskDNSDo
	Where(conds ...gen.Condition) IRiskDNSDo
	Order(conds ...field.Expr) IRiskDNSDo
	Distinct(cols ...field.Expr) IRiskDNSDo
	Omit(cols ...field.Expr) IRiskDNSDo
	Join(table schema.Tabler, on ...field.Expr) IRiskDNSDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRiskDNSDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRiskDNSDo
	Group(cols ...field.Expr) IRiskDNSDo
	Having(conds ...gen.Condition) IRiskDNSDo
	Limit(limit int) IRiskDNSDo
	Offset(offset int) IRiskDNSDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRiskDNSDo
	Unscoped() IRiskDNSDo
	Create(values ...*model.RiskDNS) error
	CreateInBatches(values []*model.RiskDNS, batchSize int) error
	Save(values ...*model.RiskDNS) error
	First() (*model.RiskDNS, error)
	Take() (*model.RiskDNS, error)
	Last() (*model.RiskDNS, error)
	Find() ([]*model.RiskDNS, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RiskDNS, err error)
	FindInBatches(result *[]*model.RiskDNS, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RiskDNS) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRiskDNSDo
	Assign(attrs ...field.AssignExpr) IRiskDNSDo
	Joins(fields ...field.RelationField) IRiskDNSDo
	Preload(fields ...field.RelationField) IRiskDNSDo
	FirstOrInit() (*model.RiskDNS, error)
	FirstOrCreate() (*model.RiskDNS, error)
	FindByPage(offset int, limit int) (result []*model.RiskDNS, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRiskDNSDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r riskDNSDo) Debug() IRiskDNSDo {
	return r.withDO(r.DO.Debug())
}

func (r riskDNSDo) WithContext(ctx context.Context) IRiskDNSDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r riskDNSDo) ReadDB() IRiskDNSDo {
	return r.Clauses(dbresolver.Read)
}

func (r riskDNSDo) WriteDB() IRiskDNSDo {
	return r.Clauses(dbresolver.Write)
}

func (r riskDNSDo) Session(config *gorm.Session) IRiskDNSDo {
	return r.withDO(r.DO.Session(config))
}

func (r riskDNSDo) Clauses(conds ...clause.Expression) IRiskDNSDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r riskDNSDo) Returning(value interface{}, columns ...string) IRiskDNSDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r riskDNSDo) Not(conds ...gen.Condition) IRiskDNSDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r riskDNSDo) Or(conds ...gen.Condition) IRiskDNSDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r riskDNSDo) Select(conds ...field.Expr) IRiskDNSDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r riskDNSDo) Where(conds ...gen.Condition) IRiskDNSDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r riskDNSDo) Order(conds ...field.Expr) IRiskDNSDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r riskDNSDo) Distinct(cols ...field.Expr) IRiskDNSDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r riskDNSDo) Omit(cols ...field.Expr) IRiskDNSDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r riskDNSDo) Join(table schema.Tabler, on ...field.Expr) IRiskDNSDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r riskDNSDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRiskDNSDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r riskDNSDo) RightJoin(table schema.Tabler, on ...field.Expr) IRiskDNSDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r riskDNSDo) Group(cols ...field.Expr) IRiskDNSDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r riskDNSDo) Having(conds ...gen.Condition) IRiskDNSDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r riskDNSDo) Limit(limit int) IRiskDNSDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r riskDNSDo) Offset(offset int) IRiskDNSDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r riskDNSDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRiskDNSDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r riskDNSDo) Unscoped() IRiskDNSDo {
	return r.withDO(r.DO.Unscoped())
}

func (r riskDNSDo) Create(values ...*model.RiskDNS) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r riskDNSDo) CreateInBatches(values []*model.RiskDNS, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r riskDNSDo) Save(values ...*model.RiskDNS) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r riskDNSDo) First() (*model.RiskDNS, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) Take() (*model.RiskDNS, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) Last() (*model.RiskDNS, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) Find() ([]*model.RiskDNS, error) {
	result, err := r.DO.Find()
	return result.([]*model.RiskDNS), err
}

func (r riskDNSDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RiskDNS, err error) {
	buf := make([]*model.RiskDNS, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r riskDNSDo) FindInBatches(result *[]*model.RiskDNS, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r riskDNSDo) Attrs(attrs ...field.AssignExpr) IRiskDNSDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r riskDNSDo) Assign(attrs ...field.AssignExpr) IRiskDNSDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r riskDNSDo) Joins(fields ...field.RelationField) IRiskDNSDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r riskDNSDo) Preload(fields ...field.RelationField) IRiskDNSDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r riskDNSDo) FirstOrInit() (*model.RiskDNS, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) FirstOrCreate() (*model.RiskDNS, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) FindByPage(offset int, limit int) (result []*model.RiskDNS, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r riskDNSDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r riskDNSDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r riskDNSDo) Delete(models ...*model.RiskDNS) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *riskDNSDo) withDO(do gen.Dao) *riskDNSDo {
	r.DO = *do.(*gen.DO)
	return r
}
