// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common/datalayer/model"
)

func newStartupFallback(db *gorm.DB, opts ...gen.DOOption) startupFallback {
	_startupFallback := startupFallback{}

	_startupFallback.startupFallbackDo.UseDB(db, opts...)
	_startupFallback.startupFallbackDo.UseModel(&model.StartupFallback{})

	tableName := _startupFallback.startupFallbackDo.TableName()
	_startupFallback.ALL = field.NewAsterisk(tableName)
	_startupFallback.ID = field.NewInt64(tableName, "id")
	_startupFallback.Logger = field.NewField(tableName, "logger")
	_startupFallback.CreatedAt = field.NewTime(tableName, "created_at")
	_startupFallback.UpdatedAt = field.NewTime(tableName, "updated_at")

	_startupFallback.fillFieldMap()

	return _startupFallback
}

type startupFallback struct {
	startupFallbackDo startupFallbackDo

	ALL       field.Asterisk
	ID        field.Int64 // ID
	Logger    field.Field // 日志输出配置
	CreatedAt field.Time  // 创建时间
	UpdatedAt field.Time  // 更新时间

	fieldMap map[string]field.Expr
}

func (s startupFallback) Table(newTableName string) *startupFallback {
	s.startupFallbackDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s startupFallback) As(alias string) *startupFallback {
	s.startupFallbackDo.DO = *(s.startupFallbackDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *startupFallback) updateTableName(table string) *startupFallback {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Logger = field.NewField(table, "logger")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *startupFallback) WithContext(ctx context.Context) IStartupFallbackDo {
	return s.startupFallbackDo.WithContext(ctx)
}

func (s startupFallback) TableName() string { return s.startupFallbackDo.TableName() }

func (s startupFallback) Alias() string { return s.startupFallbackDo.Alias() }

func (s startupFallback) Columns(cols ...field.Expr) gen.Columns {
	return s.startupFallbackDo.Columns(cols...)
}

func (s *startupFallback) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *startupFallback) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["id"] = s.ID
	s.fieldMap["logger"] = s.Logger
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s startupFallback) clone(db *gorm.DB) startupFallback {
	s.startupFallbackDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s startupFallback) replaceDB(db *gorm.DB) startupFallback {
	s.startupFallbackDo.ReplaceDB(db)
	return s
}

type startupFallbackDo struct{ gen.DO }

type IStartupFallbackDo interface {
	gen.SubQuery
	Debug() IStartupFallbackDo
	WithContext(ctx context.Context) IStartupFallbackDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStartupFallbackDo
	WriteDB() IStartupFallbackDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStartupFallbackDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStartupFallbackDo
	Not(conds ...gen.Condition) IStartupFallbackDo
	Or(conds ...gen.Condition) IStartupFallbackDo
	Select(conds ...field.Expr) IStartupFallbackDo
	Where(conds ...gen.Condition) IStartupFallbackDo
	Order(conds ...field.Expr) IStartupFallbackDo
	Distinct(cols ...field.Expr) IStartupFallbackDo
	Omit(cols ...field.Expr) IStartupFallbackDo
	Join(table schema.Tabler, on ...field.Expr) IStartupFallbackDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStartupFallbackDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStartupFallbackDo
	Group(cols ...field.Expr) IStartupFallbackDo
	Having(conds ...gen.Condition) IStartupFallbackDo
	Limit(limit int) IStartupFallbackDo
	Offset(offset int) IStartupFallbackDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStartupFallbackDo
	Unscoped() IStartupFallbackDo
	Create(values ...*model.StartupFallback) error
	CreateInBatches(values []*model.StartupFallback, batchSize int) error
	Save(values ...*model.StartupFallback) error
	First() (*model.StartupFallback, error)
	Take() (*model.StartupFallback, error)
	Last() (*model.StartupFallback, error)
	Find() ([]*model.StartupFallback, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StartupFallback, err error)
	FindInBatches(result *[]*model.StartupFallback, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StartupFallback) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStartupFallbackDo
	Assign(attrs ...field.AssignExpr) IStartupFallbackDo
	Joins(fields ...field.RelationField) IStartupFallbackDo
	Preload(fields ...field.RelationField) IStartupFallbackDo
	FirstOrInit() (*model.StartupFallback, error)
	FirstOrCreate() (*model.StartupFallback, error)
	FindByPage(offset int, limit int) (result []*model.StartupFallback, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStartupFallbackDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s startupFallbackDo) Debug() IStartupFallbackDo {
	return s.withDO(s.DO.Debug())
}

func (s startupFallbackDo) WithContext(ctx context.Context) IStartupFallbackDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s startupFallbackDo) ReadDB() IStartupFallbackDo {
	return s.Clauses(dbresolver.Read)
}

func (s startupFallbackDo) WriteDB() IStartupFallbackDo {
	return s.Clauses(dbresolver.Write)
}

func (s startupFallbackDo) Session(config *gorm.Session) IStartupFallbackDo {
	return s.withDO(s.DO.Session(config))
}

func (s startupFallbackDo) Clauses(conds ...clause.Expression) IStartupFallbackDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s startupFallbackDo) Returning(value interface{}, columns ...string) IStartupFallbackDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s startupFallbackDo) Not(conds ...gen.Condition) IStartupFallbackDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s startupFallbackDo) Or(conds ...gen.Condition) IStartupFallbackDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s startupFallbackDo) Select(conds ...field.Expr) IStartupFallbackDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s startupFallbackDo) Where(conds ...gen.Condition) IStartupFallbackDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s startupFallbackDo) Order(conds ...field.Expr) IStartupFallbackDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s startupFallbackDo) Distinct(cols ...field.Expr) IStartupFallbackDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s startupFallbackDo) Omit(cols ...field.Expr) IStartupFallbackDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s startupFallbackDo) Join(table schema.Tabler, on ...field.Expr) IStartupFallbackDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s startupFallbackDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStartupFallbackDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s startupFallbackDo) RightJoin(table schema.Tabler, on ...field.Expr) IStartupFallbackDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s startupFallbackDo) Group(cols ...field.Expr) IStartupFallbackDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s startupFallbackDo) Having(conds ...gen.Condition) IStartupFallbackDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s startupFallbackDo) Limit(limit int) IStartupFallbackDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s startupFallbackDo) Offset(offset int) IStartupFallbackDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s startupFallbackDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStartupFallbackDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s startupFallbackDo) Unscoped() IStartupFallbackDo {
	return s.withDO(s.DO.Unscoped())
}

func (s startupFallbackDo) Create(values ...*model.StartupFallback) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s startupFallbackDo) CreateInBatches(values []*model.StartupFallback, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s startupFallbackDo) Save(values ...*model.StartupFallback) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s startupFallbackDo) First() (*model.StartupFallback, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StartupFallback), nil
	}
}

func (s startupFallbackDo) Take() (*model.StartupFallback, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StartupFallback), nil
	}
}

func (s startupFallbackDo) Last() (*model.StartupFallback, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StartupFallback), nil
	}
}

func (s startupFallbackDo) Find() ([]*model.StartupFallback, error) {
	result, err := s.DO.Find()
	return result.([]*model.StartupFallback), err
}

func (s startupFallbackDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StartupFallback, err error) {
	buf := make([]*model.StartupFallback, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s startupFallbackDo) FindInBatches(result *[]*model.StartupFallback, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s startupFallbackDo) Attrs(attrs ...field.AssignExpr) IStartupFallbackDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s startupFallbackDo) Assign(attrs ...field.AssignExpr) IStartupFallbackDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s startupFallbackDo) Joins(fields ...field.RelationField) IStartupFallbackDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s startupFallbackDo) Preload(fields ...field.RelationField) IStartupFallbackDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s startupFallbackDo) FirstOrInit() (*model.StartupFallback, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StartupFallback), nil
	}
}

func (s startupFallbackDo) FirstOrCreate() (*model.StartupFallback, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StartupFallback), nil
	}
}

func (s startupFallbackDo) FindByPage(offset int, limit int) (result []*model.StartupFallback, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s startupFallbackDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s startupFallbackDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s startupFallbackDo) Delete(models ...*model.StartupFallback) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *startupFallbackDo) withDO(do gen.Dao) *startupFallbackDo {
	s.DO = *do.(*gen.DO)
	return s
}
