// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common/datalayer/model"
)

func newThirdCustomized(db *gorm.DB, opts ...gen.DOOption) thirdCustomized {
	_thirdCustomized := thirdCustomized{}

	_thirdCustomized.thirdCustomizedDo.UseDB(db, opts...)
	_thirdCustomized.thirdCustomizedDo.UseModel(&model.ThirdCustomized{})

	tableName := _thirdCustomized.thirdCustomizedDo.TableName()
	_thirdCustomized.ALL = field.NewAsterisk(tableName)
	_thirdCustomized.ID = field.NewInt64(tableName, "id")
	_thirdCustomized.Name = field.NewString(tableName, "name")
	_thirdCustomized.Icon = field.NewString(tableName, "icon")
	_thirdCustomized.Remark = field.NewString(tableName, "remark")
	_thirdCustomized.CreatedAt = field.NewTime(tableName, "created_at")
	_thirdCustomized.UpdatedAt = field.NewTime(tableName, "updated_at")

	_thirdCustomized.fillFieldMap()

	return _thirdCustomized
}

type thirdCustomized struct {
	thirdCustomizedDo thirdCustomizedDo

	ALL       field.Asterisk
	ID        field.Int64  // ID
	Name      field.String // 标签名
	Icon      field.String // 图标
	Remark    field.String // 备注
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (t thirdCustomized) Table(newTableName string) *thirdCustomized {
	t.thirdCustomizedDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t thirdCustomized) As(alias string) *thirdCustomized {
	t.thirdCustomizedDo.DO = *(t.thirdCustomizedDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *thirdCustomized) updateTableName(table string) *thirdCustomized {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Name = field.NewString(table, "name")
	t.Icon = field.NewString(table, "icon")
	t.Remark = field.NewString(table, "remark")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *thirdCustomized) WithContext(ctx context.Context) IThirdCustomizedDo {
	return t.thirdCustomizedDo.WithContext(ctx)
}

func (t thirdCustomized) TableName() string { return t.thirdCustomizedDo.TableName() }

func (t thirdCustomized) Alias() string { return t.thirdCustomizedDo.Alias() }

func (t thirdCustomized) Columns(cols ...field.Expr) gen.Columns {
	return t.thirdCustomizedDo.Columns(cols...)
}

func (t *thirdCustomized) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *thirdCustomized) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["icon"] = t.Icon
	t.fieldMap["remark"] = t.Remark
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t thirdCustomized) clone(db *gorm.DB) thirdCustomized {
	t.thirdCustomizedDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t thirdCustomized) replaceDB(db *gorm.DB) thirdCustomized {
	t.thirdCustomizedDo.ReplaceDB(db)
	return t
}

type thirdCustomizedDo struct{ gen.DO }

type IThirdCustomizedDo interface {
	gen.SubQuery
	Debug() IThirdCustomizedDo
	WithContext(ctx context.Context) IThirdCustomizedDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IThirdCustomizedDo
	WriteDB() IThirdCustomizedDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IThirdCustomizedDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IThirdCustomizedDo
	Not(conds ...gen.Condition) IThirdCustomizedDo
	Or(conds ...gen.Condition) IThirdCustomizedDo
	Select(conds ...field.Expr) IThirdCustomizedDo
	Where(conds ...gen.Condition) IThirdCustomizedDo
	Order(conds ...field.Expr) IThirdCustomizedDo
	Distinct(cols ...field.Expr) IThirdCustomizedDo
	Omit(cols ...field.Expr) IThirdCustomizedDo
	Join(table schema.Tabler, on ...field.Expr) IThirdCustomizedDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IThirdCustomizedDo
	RightJoin(table schema.Tabler, on ...field.Expr) IThirdCustomizedDo
	Group(cols ...field.Expr) IThirdCustomizedDo
	Having(conds ...gen.Condition) IThirdCustomizedDo
	Limit(limit int) IThirdCustomizedDo
	Offset(offset int) IThirdCustomizedDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IThirdCustomizedDo
	Unscoped() IThirdCustomizedDo
	Create(values ...*model.ThirdCustomized) error
	CreateInBatches(values []*model.ThirdCustomized, batchSize int) error
	Save(values ...*model.ThirdCustomized) error
	First() (*model.ThirdCustomized, error)
	Take() (*model.ThirdCustomized, error)
	Last() (*model.ThirdCustomized, error)
	Find() ([]*model.ThirdCustomized, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ThirdCustomized, err error)
	FindInBatches(result *[]*model.ThirdCustomized, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ThirdCustomized) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IThirdCustomizedDo
	Assign(attrs ...field.AssignExpr) IThirdCustomizedDo
	Joins(fields ...field.RelationField) IThirdCustomizedDo
	Preload(fields ...field.RelationField) IThirdCustomizedDo
	FirstOrInit() (*model.ThirdCustomized, error)
	FirstOrCreate() (*model.ThirdCustomized, error)
	FindByPage(offset int, limit int) (result []*model.ThirdCustomized, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IThirdCustomizedDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t thirdCustomizedDo) Debug() IThirdCustomizedDo {
	return t.withDO(t.DO.Debug())
}

func (t thirdCustomizedDo) WithContext(ctx context.Context) IThirdCustomizedDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t thirdCustomizedDo) ReadDB() IThirdCustomizedDo {
	return t.Clauses(dbresolver.Read)
}

func (t thirdCustomizedDo) WriteDB() IThirdCustomizedDo {
	return t.Clauses(dbresolver.Write)
}

func (t thirdCustomizedDo) Session(config *gorm.Session) IThirdCustomizedDo {
	return t.withDO(t.DO.Session(config))
}

func (t thirdCustomizedDo) Clauses(conds ...clause.Expression) IThirdCustomizedDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t thirdCustomizedDo) Returning(value interface{}, columns ...string) IThirdCustomizedDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t thirdCustomizedDo) Not(conds ...gen.Condition) IThirdCustomizedDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t thirdCustomizedDo) Or(conds ...gen.Condition) IThirdCustomizedDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t thirdCustomizedDo) Select(conds ...field.Expr) IThirdCustomizedDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t thirdCustomizedDo) Where(conds ...gen.Condition) IThirdCustomizedDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t thirdCustomizedDo) Order(conds ...field.Expr) IThirdCustomizedDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t thirdCustomizedDo) Distinct(cols ...field.Expr) IThirdCustomizedDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t thirdCustomizedDo) Omit(cols ...field.Expr) IThirdCustomizedDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t thirdCustomizedDo) Join(table schema.Tabler, on ...field.Expr) IThirdCustomizedDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t thirdCustomizedDo) LeftJoin(table schema.Tabler, on ...field.Expr) IThirdCustomizedDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t thirdCustomizedDo) RightJoin(table schema.Tabler, on ...field.Expr) IThirdCustomizedDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t thirdCustomizedDo) Group(cols ...field.Expr) IThirdCustomizedDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t thirdCustomizedDo) Having(conds ...gen.Condition) IThirdCustomizedDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t thirdCustomizedDo) Limit(limit int) IThirdCustomizedDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t thirdCustomizedDo) Offset(offset int) IThirdCustomizedDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t thirdCustomizedDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IThirdCustomizedDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t thirdCustomizedDo) Unscoped() IThirdCustomizedDo {
	return t.withDO(t.DO.Unscoped())
}

func (t thirdCustomizedDo) Create(values ...*model.ThirdCustomized) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t thirdCustomizedDo) CreateInBatches(values []*model.ThirdCustomized, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t thirdCustomizedDo) Save(values ...*model.ThirdCustomized) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t thirdCustomizedDo) First() (*model.ThirdCustomized, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ThirdCustomized), nil
	}
}

func (t thirdCustomizedDo) Take() (*model.ThirdCustomized, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ThirdCustomized), nil
	}
}

func (t thirdCustomizedDo) Last() (*model.ThirdCustomized, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ThirdCustomized), nil
	}
}

func (t thirdCustomizedDo) Find() ([]*model.ThirdCustomized, error) {
	result, err := t.DO.Find()
	return result.([]*model.ThirdCustomized), err
}

func (t thirdCustomizedDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ThirdCustomized, err error) {
	buf := make([]*model.ThirdCustomized, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t thirdCustomizedDo) FindInBatches(result *[]*model.ThirdCustomized, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t thirdCustomizedDo) Attrs(attrs ...field.AssignExpr) IThirdCustomizedDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t thirdCustomizedDo) Assign(attrs ...field.AssignExpr) IThirdCustomizedDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t thirdCustomizedDo) Joins(fields ...field.RelationField) IThirdCustomizedDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t thirdCustomizedDo) Preload(fields ...field.RelationField) IThirdCustomizedDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t thirdCustomizedDo) FirstOrInit() (*model.ThirdCustomized, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ThirdCustomized), nil
	}
}

func (t thirdCustomizedDo) FirstOrCreate() (*model.ThirdCustomized, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ThirdCustomized), nil
	}
}

func (t thirdCustomizedDo) FindByPage(offset int, limit int) (result []*model.ThirdCustomized, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t thirdCustomizedDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t thirdCustomizedDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t thirdCustomizedDo) Delete(models ...*model.ThirdCustomized) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *thirdCustomizedDo) withDO(do gen.Dao) *thirdCustomizedDo {
	t.DO = *do.(*gen.DO)
	return t
}
