// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common/datalayer/model"
)

func newVictoriaMetrics(db *gorm.DB, opts ...gen.DOOption) victoriaMetrics {
	_victoriaMetrics := victoriaMetrics{}

	_victoriaMetrics.victoriaMetricsDo.UseDB(db, opts...)
	_victoriaMetrics.victoriaMetricsDo.UseModel(&model.VictoriaMetrics{})

	tableName := _victoriaMetrics.victoriaMetricsDo.TableName()
	_victoriaMetrics.ALL = field.NewAsterisk(tableName)
	_victoriaMetrics.ID = field.NewInt64(tableName, "id")
	_victoriaMetrics.Enabled = field.NewBool(tableName, "enabled")
	_victoriaMetrics.URL = field.NewString(tableName, "url")
	_victoriaMetrics.Method = field.NewString(tableName, "method")
	_victoriaMetrics.Header = field.NewField(tableName, "header")
	_victoriaMetrics.CreatedAt = field.NewTime(tableName, "created_at")
	_victoriaMetrics.UpdatedAt = field.NewTime(tableName, "updated_at")

	_victoriaMetrics.fillFieldMap()

	return _victoriaMetrics
}

type victoriaMetrics struct {
	victoriaMetricsDo victoriaMetricsDo

	ALL       field.Asterisk
	ID        field.Int64  // ID
	Enabled   field.Bool   // 是否启用
	URL       field.String // 推送地址
	Method    field.String // 请求方法
	Header    field.Field  // Header
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (v victoriaMetrics) Table(newTableName string) *victoriaMetrics {
	v.victoriaMetricsDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v victoriaMetrics) As(alias string) *victoriaMetrics {
	v.victoriaMetricsDo.DO = *(v.victoriaMetricsDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *victoriaMetrics) updateTableName(table string) *victoriaMetrics {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.Enabled = field.NewBool(table, "enabled")
	v.URL = field.NewString(table, "url")
	v.Method = field.NewString(table, "method")
	v.Header = field.NewField(table, "header")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *victoriaMetrics) WithContext(ctx context.Context) IVictoriaMetricsDo {
	return v.victoriaMetricsDo.WithContext(ctx)
}

func (v victoriaMetrics) TableName() string { return v.victoriaMetricsDo.TableName() }

func (v victoriaMetrics) Alias() string { return v.victoriaMetricsDo.Alias() }

func (v victoriaMetrics) Columns(cols ...field.Expr) gen.Columns {
	return v.victoriaMetricsDo.Columns(cols...)
}

func (v *victoriaMetrics) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *victoriaMetrics) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 7)
	v.fieldMap["id"] = v.ID
	v.fieldMap["enabled"] = v.Enabled
	v.fieldMap["url"] = v.URL
	v.fieldMap["method"] = v.Method
	v.fieldMap["header"] = v.Header
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v victoriaMetrics) clone(db *gorm.DB) victoriaMetrics {
	v.victoriaMetricsDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v victoriaMetrics) replaceDB(db *gorm.DB) victoriaMetrics {
	v.victoriaMetricsDo.ReplaceDB(db)
	return v
}

type victoriaMetricsDo struct{ gen.DO }

type IVictoriaMetricsDo interface {
	gen.SubQuery
	Debug() IVictoriaMetricsDo
	WithContext(ctx context.Context) IVictoriaMetricsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVictoriaMetricsDo
	WriteDB() IVictoriaMetricsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVictoriaMetricsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVictoriaMetricsDo
	Not(conds ...gen.Condition) IVictoriaMetricsDo
	Or(conds ...gen.Condition) IVictoriaMetricsDo
	Select(conds ...field.Expr) IVictoriaMetricsDo
	Where(conds ...gen.Condition) IVictoriaMetricsDo
	Order(conds ...field.Expr) IVictoriaMetricsDo
	Distinct(cols ...field.Expr) IVictoriaMetricsDo
	Omit(cols ...field.Expr) IVictoriaMetricsDo
	Join(table schema.Tabler, on ...field.Expr) IVictoriaMetricsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVictoriaMetricsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVictoriaMetricsDo
	Group(cols ...field.Expr) IVictoriaMetricsDo
	Having(conds ...gen.Condition) IVictoriaMetricsDo
	Limit(limit int) IVictoriaMetricsDo
	Offset(offset int) IVictoriaMetricsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVictoriaMetricsDo
	Unscoped() IVictoriaMetricsDo
	Create(values ...*model.VictoriaMetrics) error
	CreateInBatches(values []*model.VictoriaMetrics, batchSize int) error
	Save(values ...*model.VictoriaMetrics) error
	First() (*model.VictoriaMetrics, error)
	Take() (*model.VictoriaMetrics, error)
	Last() (*model.VictoriaMetrics, error)
	Find() ([]*model.VictoriaMetrics, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VictoriaMetrics, err error)
	FindInBatches(result *[]*model.VictoriaMetrics, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.VictoriaMetrics) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVictoriaMetricsDo
	Assign(attrs ...field.AssignExpr) IVictoriaMetricsDo
	Joins(fields ...field.RelationField) IVictoriaMetricsDo
	Preload(fields ...field.RelationField) IVictoriaMetricsDo
	FirstOrInit() (*model.VictoriaMetrics, error)
	FirstOrCreate() (*model.VictoriaMetrics, error)
	FindByPage(offset int, limit int) (result []*model.VictoriaMetrics, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVictoriaMetricsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v victoriaMetricsDo) Debug() IVictoriaMetricsDo {
	return v.withDO(v.DO.Debug())
}

func (v victoriaMetricsDo) WithContext(ctx context.Context) IVictoriaMetricsDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v victoriaMetricsDo) ReadDB() IVictoriaMetricsDo {
	return v.Clauses(dbresolver.Read)
}

func (v victoriaMetricsDo) WriteDB() IVictoriaMetricsDo {
	return v.Clauses(dbresolver.Write)
}

func (v victoriaMetricsDo) Session(config *gorm.Session) IVictoriaMetricsDo {
	return v.withDO(v.DO.Session(config))
}

func (v victoriaMetricsDo) Clauses(conds ...clause.Expression) IVictoriaMetricsDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v victoriaMetricsDo) Returning(value interface{}, columns ...string) IVictoriaMetricsDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v victoriaMetricsDo) Not(conds ...gen.Condition) IVictoriaMetricsDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v victoriaMetricsDo) Or(conds ...gen.Condition) IVictoriaMetricsDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v victoriaMetricsDo) Select(conds ...field.Expr) IVictoriaMetricsDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v victoriaMetricsDo) Where(conds ...gen.Condition) IVictoriaMetricsDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v victoriaMetricsDo) Order(conds ...field.Expr) IVictoriaMetricsDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v victoriaMetricsDo) Distinct(cols ...field.Expr) IVictoriaMetricsDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v victoriaMetricsDo) Omit(cols ...field.Expr) IVictoriaMetricsDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v victoriaMetricsDo) Join(table schema.Tabler, on ...field.Expr) IVictoriaMetricsDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v victoriaMetricsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVictoriaMetricsDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v victoriaMetricsDo) RightJoin(table schema.Tabler, on ...field.Expr) IVictoriaMetricsDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v victoriaMetricsDo) Group(cols ...field.Expr) IVictoriaMetricsDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v victoriaMetricsDo) Having(conds ...gen.Condition) IVictoriaMetricsDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v victoriaMetricsDo) Limit(limit int) IVictoriaMetricsDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v victoriaMetricsDo) Offset(offset int) IVictoriaMetricsDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v victoriaMetricsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVictoriaMetricsDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v victoriaMetricsDo) Unscoped() IVictoriaMetricsDo {
	return v.withDO(v.DO.Unscoped())
}

func (v victoriaMetricsDo) Create(values ...*model.VictoriaMetrics) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v victoriaMetricsDo) CreateInBatches(values []*model.VictoriaMetrics, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v victoriaMetricsDo) Save(values ...*model.VictoriaMetrics) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v victoriaMetricsDo) First() (*model.VictoriaMetrics, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetrics), nil
	}
}

func (v victoriaMetricsDo) Take() (*model.VictoriaMetrics, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetrics), nil
	}
}

func (v victoriaMetricsDo) Last() (*model.VictoriaMetrics, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetrics), nil
	}
}

func (v victoriaMetricsDo) Find() ([]*model.VictoriaMetrics, error) {
	result, err := v.DO.Find()
	return result.([]*model.VictoriaMetrics), err
}

func (v victoriaMetricsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VictoriaMetrics, err error) {
	buf := make([]*model.VictoriaMetrics, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v victoriaMetricsDo) FindInBatches(result *[]*model.VictoriaMetrics, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v victoriaMetricsDo) Attrs(attrs ...field.AssignExpr) IVictoriaMetricsDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v victoriaMetricsDo) Assign(attrs ...field.AssignExpr) IVictoriaMetricsDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v victoriaMetricsDo) Joins(fields ...field.RelationField) IVictoriaMetricsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v victoriaMetricsDo) Preload(fields ...field.RelationField) IVictoriaMetricsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v victoriaMetricsDo) FirstOrInit() (*model.VictoriaMetrics, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetrics), nil
	}
}

func (v victoriaMetricsDo) FirstOrCreate() (*model.VictoriaMetrics, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetrics), nil
	}
}

func (v victoriaMetricsDo) FindByPage(offset int, limit int) (result []*model.VictoriaMetrics, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v victoriaMetricsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v victoriaMetricsDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v victoriaMetricsDo) Delete(models ...*model.VictoriaMetrics) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *victoriaMetricsDo) withDO(do gen.Dao) *victoriaMetricsDo {
	v.DO = *do.(*gen.DO)
	return v
}
